server:
  port: 8090
spring:
  thymeleaf:
    cache: false
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:h2:mem:test;
    username: postgres
    password: 1234
    driver-class-name: org.h2.Driver